version: '3'

services:
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./FrontEnd:/app
    environment:
      FLASK_ENV: development

  backend:
    build:
      context: ./BackEnd-API
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./BackEnd-API:/app
    environment:
      FLASK_ENV: development