version: '3'

services:
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./FrontEnd:/app
    environment:
      FLASK_ENV: development

  backend:
    build:
      context: ./BackEnd-API
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./BackEnd-API:/app
    environment:
      FLASK_ENV: development

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "a"
      MYSQL_DATABASE: proyecto_messi
    volumes:
      - ./BackEnd-API/proyecto_messi.sql:/docker-entrypoint-initdb.d/proyecto_messi.sql