version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    build: .
    container_name: baseArtemisa
    environment:
      MYSQL_DATABASE: hotelArtemisa
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
       - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql